### ISSUE TITLE
Compilation time

### ISSUE THREAD

**Issue by maxdd** [visore/QRealFourier#2]
Could you please state an average compilation time? I'm integrating your lib inside QtCreator and it seems it takes a lot. I noticed that my *.obj files are produced except for qfourierfixedcalculator.obj which is stuck at 0kb. I can't succesfully compile :(

I'm compiling with VS2013

**Comment by visore** [comment]
Should take +- 15 seconds. I'm using gcc, so I can't help you with VS2013.

qfourierfixedcalculator has template classes which are generated during compile time. Hence, the problem might be with the templates.

I've created an alternative for you: https://www.dropbox.com/s/cr1wtuahrd7ji31/qrealfourier.zip?dl=0

Replace the 2 files with the ones in the zip and try again. If that solves the problem, then there is probably a bug in VS. If not, send me the error output and I'll see if I can don something about it.

**Comment by maxdd** [comment]
Hello,
thank you for your fast answer. Let me give you some more information so that you have the global situation.
1. As per others libraries, i've imported your *.h and *.cpp files into a QtConsole Application Project

![prj](https://cloud.githubusercontent.com/assets/6155973/7901042/bf6fb31e-0775-11e5-83e8-3d8d6c1bbaa7.PNG)
1. The compilation output from QtCreator doesn't report any errors, the only stuff it prints are warnings. See here http://pastebin.com/CQn2N8WL
2. The main.cpp file is your example1.cpp file

Edit 1: In Debug mode the compilation works!!!! Is there a reason why i can't compile in release mode?

**Comment by visore** [comment]
Yeah, my library is build on top of the FFTReal library, that is what is causing all the warnings. Simply ignore the warnings, they don't matter (or just disable warnings in Qt Creator).
1. Did you try it using the other two files I've uploaded on dropbox? Is the problem still the same?
2. How long did you wait for it to compile? What is the last compilation instruction in Qt Creator when the compilation is stuck?
3. Is there any specific reason why you are using Microsoft's VC in Qt? If not, why not try the MinGW version of Qt (http://download.qt.io/official_releases/qt/5.4/5.4.1/qt-opensource-windows-x86-mingw491_opengl-5.4.1.exe).
4. It is really strange that the debug mode works and not the release mode. This seems to me like a problem in the compiler.

**Comment by maxdd** [comment]
1. Yes i've tried them ... they don't work in release mode too
2. In debug i wait like 30s or less while in release mode i've reached 6+ mins then i stopped it
3. I'm using VC2013 because i thought it was the best compiler

**Comment by visore** [comment]
Ok, then I have no clue what's going wrong. The template classes are very basic, so there is nothing weird that I can see that causes the problem.

My suggestion would be to use the MinGW Qt version. MinGW is based on gcc and from my experience it has fewer problems than VC, especially when working with Qt.

Sorry for not being able to help more. But this seems to be a compiler issue and nothing related to the code. There were two people who also used this lib and compiled with VC and it worked without a problem. Maybe something is wrong with your VC. Maybe updating it would help. Otherwise go with the MinGW route. You don't have to do much. Just uninstall your current Qt, download and install the one I gave in the previous link. (or switch over to Linux ;-0).

**Comment by visore** [comment]
If you send me the entire Qt project, I can test it on my side.

**Comment by maxdd** [comment]
I solved it using mingw... it worked both in release and debug mode... a vs2013 problem it seems

**Comment by visore** [comment]
Glad it works now.
